// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the app actually did, as opposed to what it attempted. The UI renders
 * "Already running" from this rather than from a hand-written string, so it
 * cannot claim credit for work it did not do.
 */
export type ActionTaken = "started" | "already_running" | "no_action_needed" | "skipped" | "not_attempted";
