// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileDiff } from "./FileDiff";

/**
 * A preview across every file an adapter touches, plus what it could not do.
 */
export type AdapterPreview = { files: Array<FileDiff>, warnings: Array<string>, };
