// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileEdits } from "./FileEdits";

export type AdapterPlan = { adapterId: string, files: Array<FileEdits>, 
/**
 * Things the plan could not express. Reported, never silently averaged.
 */
warnings: Array<string>, };
