// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlassLevel } from "./GlassLevel";

export type Appearance = { 
/**
 * `#RRGGBB`. Every interactive and highlight colour in the UI derives from
 * this one value.
 */
accent: string, 
/**
 * How much translucency and blur the chrome uses.
 */
glass: GlassLevel, 
/**
 * Suppresses the few transitions the app uses. The OS
 * `prefers-reduced-motion` setting also does this; whichever asks, wins.
 */
reduceMotion: boolean, };
