// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Everything the UI needs to describe the running app, on the dashboard and
 * in a support ticket.
 */
export type AppInfo = { version: string, 
/**
 * Which milestone this build represents. Shown in the UI so a bug report
 * says what was actually built, not what was planned.
 */
milestone: number, 
/**
 * True when running against fixtures. The UI shows a persistent banner so
 * a screenshot can never be mistaken for real hardware.
 */
simulated: boolean, dpiAwareness: string, dpiAwarenessOk: boolean, logDir: string, };
