// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppliedAdapterInfo = { 
/**
 * The backup this write can be undone from.
 */
backup: string, written: Array<string>, };
