// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayMode } from "./DisplayMode";

/**
 * The modes one output can actually run, as the driver reports them.
 */
export type AvailableModes = { devicePath: string, modes: Array<DisplayMode>, };
