// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AxisReading = { name: string, 
/**
 * -1.0 to 1.0.
 */
value: number, 
/**
 * 0.0 to 1.0. What a pedal wants: at rest is empty, not half full.
 */
unipolar: number, };
