// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One backed-up operation, for the restore list.
 */
export type BackupInfo = { id: string, takenAt: string, 
/**
 * What caused the write — an adapter id, usually.
 */
reason: string, files: Array<string>, };
