// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResidualInfo } from "./ResidualInfo";

/**
 * A single set of triple-screen values fitted to a rig that is not uniform.
 */
export type BestFitInfo = { widthMm: number, heightMm: number, bezelMm: number, distanceMm: number, angleDeg: number, worstErrorDeg: number, 
/**
 * True when the rig is uniform enough that this is exact rather than a
 * compromise. The UI must never present a fit as exact when it is not.
 */
isExact: boolean, residuals: Array<ResidualInfo>, };
