// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Mm } from "./Mm";

/**
 * Per-edge bezel: the dark border between the visible image and the outside of
 * the chassis. Measured per edge because left/right routinely differ from
 * top/bottom, and the two side panels of a rig are often not a matched pair.
 */
export type Bezel = { left: Mm, right: Mm, top: Mm, bottom: Mm, };
