// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BindingDrift = { expectedSlot: number | null, actualSlot: number | null, expectedInstanceGuid: string | null, actualInstanceGuid: string | null, };
