// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PixelRect } from "./PixelRect";

/**
 * A window's current geometry, learned rather than configured.
 */
export type CapturedLayout = { 
/**
 * The outer window rectangle, exactly as it is now.
 */
rect: PixelRect, borderless: boolean, alwaysOnTop: boolean, 
/**
 * Learned from the running process. This is the valuable part for a Steam
 * or Epic title: a protocol launch names no executable, so without this
 * the launcher has nothing to watch for or to match a window against.
 */
exeName: string | null, className: string, title: string, 
/**
 * The screens this window overlaps, by friendly name.
 */
covers: Array<string>, 
/**
 * True when the window exactly covers the screens it touches, with nothing
 * hanging off an edge and no screen only partly used.
 */
coversExactly: boolean, };
