// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapturedLayout } from "./CapturedLayout";
import type { OpenWindow } from "./OpenWindow";
import type { Profile } from "./Profile";

/**
 * The result of asking to copy a running game's screen setup.
 */
export type CaptureResult = { "kind": "captured", layout: CapturedLayout, 
/**
 * Boxed: a Profile is far larger than the other variants, and an enum
 * is as big as its biggest member wherever it is passed.
 */
profile: Profile, } | { "kind": "choose", windows: Array<OpenWindow>, } | { "kind": "not_running", exe: string, } | { "kind": "nothing_found" };
