// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKind } from "./DeviceKind";

export type CatalogEntry = { vid: number, pid: number, name: string, manufacturer: string, 
/**
 * What the thing is, so the UI can group and the launcher can suggest
 * which peripherals a profile probably needs.
 */
kind: DeviceKind, };
