// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigFormat } from "./ConfigFormat";
import type { Write } from "./Write";

export type ConfigFile = { pathTemplate: string, format: ConfigFormat, writes: Array<Write>, };
