// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConfigGroup = { 
/**
 * The INI section name, or empty for a flat XML listing.
 */
name: string, keys: Array<string>, };
