// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfirmOutcome } from "./ConfirmOutcome";

/**
 * Where a display change stands while the user decides.
 *
 * The countdown is owned by the backend, never by the UI: if the change made
 * the screen unreadable there is nobody to run a timer in the frontend, and
 * silence has to mean revert.
 */
export type ConfirmState = { 
/**
 * Seconds left before the change is undone. Zero once it has settled.
 */
secondsLeft: number, outcome: ConfirmOutcome | null, };
