// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How well an adapter's key names are actually known.
 *
 * Shown in the UI, because "we read this out of the shipped file" and "someone
 * on a forum said this in 2019" are different claims and should not look the
 * same.
 */
export type Confidence = "verified" | "corroborated";
