// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigFormat } from "./ConfigFormat";
import type { ConfigGroup } from "./ConfigGroup";

/**
 * What a config file actually contains, for a title nobody has confirmed yet.
 *
 * This is how a recognised-but-unwritten title becomes a real adapter without
 * anybody guessing: the app reads the file on the user's machine and reports
 * its structure, they send that in, and it becomes a catalog entry backed by a
 * real file. One round trip, no forum posts.
 */
export type ConfigInspection = { path: string, exists: boolean, format: ConfigFormat, 
/**
 * INI sections with their keys, or XML element names.
 */
groups: Array<ConfigGroup>, };
