// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Mm } from "./Mm";

export type Curvature = { "kind": "flat" } | { "kind": "radius", radius: Mm, };
