// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A curved panel resolved into what a flat-plane sim can consume.
 */
export type CurveResult = { arcMm: number, chordMm: number, sagittaMm: number, subtendedDeg: number, chordPlaneDistanceMm: number, 
/**
 * The correct answer: chord width at the chord-plane distance.
 */
hFovDeg: number, 
/**
 * What you get by naively treating the arc as a flat width. Returned
 * alongside the correct value so the UI can show the gap rather than
 * assert it — on a 49" 1000R panel it is over 15 degrees.
 */
naiveHFovDeg: number, worstCaseErrorDeg: number | null, };
