// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PixelRect } from "./PixelRect";

/**
 * A region of virtual-desktop space that maps to no physical panel. Real on
 * any rig with mismatched panel heights, and the layout editor draws them so
 * you can see where a window would vanish.
 */
export type DeadRegion = { rect: PixelRect, };
