// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An angle in degrees. Stored in degrees because that is what the user types
 * and what game config files want; converted to radians only inside math.
 */
export type Deg = number;
