// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Unit } from "./Unit";

/**
 * A number the rig model can produce, in the unit a given game wants.
 *
 * This is the vocabulary a catalog entry is written in. Every sim that does
 * triple-screen properly asks for the same handful of physical facts — they
 * differ only in units, names and file format — so the entries stay short and
 * the arithmetic lives in one place.
 */
export type Derived = { "kind": "screen_width", unit: Unit, decimals: number, } | { "kind": "screen_height", unit: Unit, decimals: number, } | { "kind": "monitor_width", unit: Unit, decimals: number, } | { "kind": "eye_distance", unit: Unit, decimals: number, } | { "kind": "bezel_gap", unit: Unit, decimals: number, } | { "kind": "side_angle", decimals: number, } | { "kind": "pixel_width" } | { "kind": "pixel_height" } | { "kind": "screen_count" } | { "kind": "literal", value: string, } | { "kind": "tuple", parts: Array<Derived>, };
