// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonitorPitch } from "./MonitorPitch";
import type { PixelRect } from "./PixelRect";

/**
 * The virtual desktop's shape, as the layout editor needs to draw it.
 */
export type DesktopLayoutInfo = { 
/**
 * The bounding box of every monitor, in physical pixels. Its origin is
 * negative whenever a monitor sits left of or above the primary.
 */
bounds: PixelRect, 
/**
 * Parts of `bounds` that map to no physical panel. A window placed here is
 * addressable and invisible.
 */
deadRegions: Array<PixelRect>, 
/**
 * Areas as f64 rather than u64: they cross into JavaScript, where an
 * integer beyond 2^53 would silently lose precision. A desktop would have
 * to be about 95 megapixels square to get near that, but `bigint` in the
 * binding for no reason is worse.
 */
coveredArea: number, deadArea: number, isGapless: boolean, 
/**
 * Per-monitor pixel pitch, in the same order as `list_monitors`.
 */
pitches: Array<MonitorPitch>, };
