// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BindingDrift } from "./BindingDrift";
import type { DeviceMode } from "./DeviceMode";
import type { DeviceRef } from "./DeviceRef";
import type { DeviceSection } from "./DeviceSection";
import type { DeviceStatus } from "./DeviceStatus";
import type { VJoyInfo } from "./VJoyInfo";

export type DetectedDevice = { device: DeviceRef, manufacturer: string | null, 
/**
 * What Windows calls it, before the catalog cleans it up. Frequently
 * "HID-compliant game controller", which is why the catalog exists.
 */
rawProductName: string | null, status: DeviceStatus, 
/**
 * Present at the HID layer.
 */
hidPresent: boolean, 
/**
 * Listed by DirectInput — i.e. games can actually see it.
 */
dinputPresent: boolean, 
/**
 * DirectInput enumeration slot. Games bind controls to this, and it can
 * change across a reboot or a hotplug, silently destroying bindings.
 */
dinputSlot: number | null, dinputInstanceGuid: string | null, 
/**
 * True when this is a vJoy virtual device rather than real hardware.
 */
isVirtual: boolean, vjoy: VJoyInfo | null, 
/**
 * Set when the device works but its DirectInput identity has moved since
 * the profile was saved. A badge on top of Connected, not a fourth state.
 */
bindingDrift: BindingDrift | null, 
/**
 * What a user-given name for this device is stored against. On the wire so
 * the UI can ask for a rename without reimplementing the identity rules —
 * two implementations of "which device is this" would disagree eventually,
 * and the symptom would be a name silently attaching to the wrong pedals.
 *
 * `#[serde(default)]` so fixture files written before this existed still
 * load; an empty key simply means nothing to rename.
 */
aliasKey: string, 
/**
 * True when `display_name` is the user's own name rather than the
 * catalog's or Windows'. Drives whether there is anything to reset.
 */
renamed: boolean, 
/**
 * Set when Windows lists this device as several controllers and this row
 * is one of them — an Asetek wheel in legacy input mode is four. Each
 * part is named on its own and bound to on its own.
 */
section: DeviceSection | null, 
/**
 * Which presentation the device is using, for the makes that have more
 * than one. `None` for everything else: a device that always looks the
 * same is in no mode at all.
 */
mode: DeviceMode | null, };
