// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BindingDrift } from "./BindingDrift";
import type { DeviceRef } from "./DeviceRef";
import type { DeviceStatus } from "./DeviceStatus";
import type { VJoyInfo } from "./VJoyInfo";

export type DetectedDevice = { device: DeviceRef, manufacturer: string | null, 
/**
 * What Windows calls it, before the catalog cleans it up. Frequently
 * "HID-compliant game controller", which is why the catalog exists.
 */
rawProductName: string | null, status: DeviceStatus, 
/**
 * Present at the HID layer.
 */
hidPresent: boolean, 
/**
 * Listed by DirectInput — i.e. games can actually see it.
 */
dinputPresent: boolean, 
/**
 * DirectInput enumeration slot. Games bind controls to this, and it can
 * change across a reboot or a hotplug, silently destroying bindings.
 */
dinputSlot: number | null, dinputInstanceGuid: string | null, 
/**
 * True when this is a vJoy virtual device rather than real hardware.
 */
isVirtual: boolean, vjoy: VJoyInfo | null, 
/**
 * Set when the device works but its DirectInput identity has moved since
 * the profile was saved. A badge on top of Connected, not a fourth state.
 */
bindingDrift: BindingDrift | null, };
