// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One part of a device that Windows lists as several controllers.
 */
export type DeviceSection = { 
/**
 * What distinguishes this part in the interface path — `mi_01&col03` —
 * and the only thing that does. Stable across reboots and ports, because
 * it comes from the device's own descriptor.
 */
id: string, 
/**
 * Its place among the parts present, counting from one, in the order
 * Windows numbers them.
 */
index: number, count: number, };
