// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceRef } from "./DeviceRef";
import type { DeviceStatus } from "./DeviceStatus";

/**
 * A timestamped status transition, so "my pedals dropped mid-race" is
 * diagnosable after the fact instead of being a mystery.
 */
export type DeviceEvent = { at: string, device: DeviceRef, from: DeviceStatus, to: DeviceStatus, reason: string, };
