// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeviceRef = { vid: number, pid: number, 
/**
 * The preferred disambiguator between two identical devices.
 */
serial: string | null, 
/**
 * Fallback when a device reports no serial. Two identical un-serialled
 * pedal sets can only be told apart by which port they are in.
 */
instancePath: string | null, 
/**
 * Always renameable by the user, whatever the catalog or Windows says.
 */
displayName: string, };
