// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of its presentations a device is using.
 *
 * Only for devices that have more than one. A device that always looks the
 * same is in no mode at all, and saying "normal mode" of it would invite the
 * question of what the other one is.
 */
export type DeviceMode = "normal" | "legacy";
