// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Resolution } from "./Resolution";

export type DisplayMode = { resolution: Resolution, refreshHz: number, bitsPerPixel: number, };
