// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EdidIdentity = { 
/**
 * Three-character PNP vendor ID, EDID bytes 0x08..0x0A.
 */
manufacturerId: string, 
/**
 * EDID bytes 0x0A..0x0C.
 */
productCode: number, 
/**
 * Descriptor 0xFF when the panel bothers to provide one. Many do not.
 */
serial: string | null, 
/**
 * EDID bytes 0x0C..0x10. Weaker than the string serial but usually present.
 */
serialNumber: number, 
/**
 * Manufacture week and year. Last-resort tiebreaker between two otherwise
 * identical un-serialled panels.
 */
weekYear: [number, number], 
/**
 * A fast path only, re-validated on every scan. Never trusted alone.
 */
cachedDevicePath: string | null, };
