// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One setting an adapter wants to write, and why.
 */
export type Edit = { section: string, key: string, value: string, 
/**
 * The reason, in the user's terms: "your centre screen is 597 mm of
 * visible glass". Shown beside the change in the diff.
 */
because: string, };
