// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Edit } from "./Edit";

/**
 * The file an adapter edits, with the path still to be resolved.
 *
 * `{documents}` and `{localappdata}` are substituted by the platform layer.
 * Keeping them as tokens is what lets a plan be built and tested on a machine
 * that has neither folder.
 */
export type FileEdits = { pathTemplate: string, edits: Array<Edit>, };
