// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MissingKey } from "./MissingKey";
import type { ValueChange } from "./ValueChange";

export type FileDiff = { path: string, 
/**
 * False when the file is not there at all — usually "the game has not been
 * run yet", which is a different problem from a wrong key.
 */
exists: boolean, changes: Array<ValueChange>, missing: Array<MissingKey>, };
