// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FixAction = { "kind": "start" } | { "kind": "retry" } | { "kind": "skip" } | { "kind": "open_settings", section: string, } | { "kind": "open_url", url: string, };
