// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The frame a window's style implies: how much bigger the outer window is
 * than its client area, on each side.
 */
export type FrameInsets = { left: number, top: number, right: number, bottom: number, };
