// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Confidence } from "./Confidence";
import type { ConfigFile } from "./ConfigFile";

export type GameEntry = { id: string, title: string, 
/**
 * Every name an install of this game goes by, normalised. Matching is
 * exact against this list — never a substring, because "Assetto Corsa
 * Competizione" contains "Assetto Corsa" and they are different games with
 * different config formats.
 */
aliases: Array<string>, confidence: Confidence, scope: string, source: string, 
/**
 * Things worth telling the user about this title that are not warnings
 * about their rig — what this adapter deliberately does not touch, and
 * where to find the rest. Shown alongside the diff.
 */
notes: Array<string>, files: Array<ConfigFile>, };
