// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaunchMethod } from "./LaunchMethod";
import type { Platform } from "./Platform";

export type GameRef = { adapterId: string, installPath: string | null, launch: LaunchMethod, 
/**
 * Which launcher this came from, kept as its own field rather than read
 * back out of `launch`. A profile outlives the install it was made from,
 * and "you had this on Steam" is still true after the game is gone.
 */
platform: Platform, 
/**
 * Cover art on disk, found once and remembered.
 *
 * A path rather than the image, so a profile stays a small readable JSON
 * file. Steam already has the artwork cached locally — no download, no
 * third-party service, nothing that stops working offline.
 */
artPath: string | null, };
