// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GapInfo = { 
/**
 * The physical dark band to the inboard neighbour: both bezels plus the
 * mount gap.
 */
mm: number, 
/**
 * `None` when the panels either side have different pixel pitch, where
 * there is no single pixel size the gap could have.
 */
px: number | null, deg: number, };
