// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Glass costs contrast, and this app is read from over 700 mm away in a dim
 * room. The level is a real setting rather than a fixed style so that the look
 * can be dialled back without the app becoming a different product.
 */
export type GlassLevel = "off" | "subtle" | "full";
