// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpuVendor } from "./GpuVendor";

/**
 * One display adapter, as the platform reported it.
 */
export type GpuInfo = { name: string, vendor: GpuVendor, 
/**
 * `number`, not `bigint`, for the reason given on `WindowTarget::timeout_ms`:
 * no quantity here is near the precision limit and a bigint needs a cast
 * at every call site.
 */
vramMb: number, 
/**
 * The Windows driver version, `32.0.16.1664` style, when it could be read.
 */
windowsDriver: string | null, 
/**
 * NVIDIA's own version number derived from it, `616.64` style.
 */
driver: string | null, };
