// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the panic hotkey is armed, and what it is.
 *
 * `registered` is read back from Windows rather than assumed: another program
 * may already own the combination, and a safety net the user believes in but
 * that does nothing is worse than none at all.
 */
export type HotkeyInfo = { combination: string, registered: boolean, };
