// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which kind of control an input alias names.
 *
 * Kept apart because the numbering restarts for each: button 1 and axis 1 are
 * different things on the same device, and a game's binding screen numbers
 * them that way too.
 */
export type InputKind = "axis" | "button" | "hat";
