// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AxisState } from "./AxisState";
import type { DeviceRef } from "./DeviceRef";

/**
 * A live snapshot of one device's axes and buttons, for the input monitor.
 * Read shared, never exclusive, and suspended entirely while a game runs so
 * the app can never steal input from the game.
 */
export type InputState = { device: DeviceRef, 
/**
 * Normalised to -1.0..=1.0.
 */
axes: Array<AxisState>, buttons: Array<boolean>, hats: Array<number>, };
