// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the monitor is doing, published alongside the frames.
 *
 * A panel that only ever showed frames could not tell "this device has not
 * moved yet" apart from "this device could not be opened at all", and the
 * second is the case a user hits: HID paths can be refused, and a failure
 * inside the reading thread used to reach nothing but the log. Every outcome
 * is on the wire so the panel can say which one happened.
 */
export type InputStatus = { "kind": "opening", instancePath: string, } | { "kind": "listening", instancePath: string, axes: Array<string>, buttons: number, } | { "kind": "suspended", instancePath: string, } | { "kind": "failed", instancePath: string, message: string, };
