// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AxisReading } from "./AxisReading";

/**
 * One frame of live input from a device.
 */
export type InputFrame = { 
/**
 * The device interface path, matching `DeviceRef.instancePath`.
 */
instancePath: string, axes: Array<AxisReading>, 
/**
 * One entry per declared button, in report order, so the UI can draw a
 * stable grid rather than a list that changes length as buttons are held.
 */
buttons: Array<boolean>, };
