// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A game found on disk, with what it takes to start it.
 */
export type InstalledGameInfo = { name: string, installPath: string, 
/**
 * "steam" or "epic". The launcher it belongs to.
 */
launcher: string, 
/**
 * The URI that starts it. Protocol launches return no process handle,
 * which is why the window matcher works from the executable name instead.
 */
launchUri: string, 
/**
 * Whether an adapter exists for this title yet. Adapters arrive in
 * milestone 10, so this is honest rather than aspirational.
 */
hasAdapter: boolean, };
