// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Remedy } from "./Remedy";

/**
 * The wire shape of every error the frontend can see. A raw OS error code
 * never reaches the UI; each variant carries enough to write a sentence a
 * person can act on.
 */
export type IpcError = { kind: string, message: string, 
/**
 * What the user can do about it, when there is something. Drives the
 * inline fix button on a failed preflight row.
 */
remedy: Remedy | null, };
