// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LaunchMethod = { "kind": "executable", path: string, args: Array<string>, workingDir: string | null, } | { "kind": "steam", appId: string, } | { "kind": "epic", appName: string, } | { "kind": "uwp", packageFamilyName: string, } | { "kind": "uri", uri: string, };
