// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A display preference only. The stored model is always millimetres; this
 * affects the input/display boundary and nothing else.
 */
export type LengthUnit = "mm" | "cm" | "inch";
