// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryMode } from "./LibraryMode";

/**
 * How the games library is drawn.
 */
export type LibraryView = { mode: LibraryMode, 
/**
 * Cover width in pixels, for the grid. A slider rather than three preset
 * sizes: a wall of boxes at 4K and a wall at 1080p want different
 * answers, and only the person looking at it knows which.
 */
artPx: number, };
