// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tier } from "./Tier";

/**
 * What the UI is told about licensing, and the whole of it.
 *
 * No key, no token, no endpoint, no machine id. A licence check whose inputs
 * the UI can see is one anyone can read out of the installer, because `src/`
 * ships as readable JavaScript.
 */
export type LicenceState = { tier: Tier, 
/**
 * The last four characters of the key. Enough for a person to tell two
 * licences apart, useless to anyone who copies it.
 */
reference: string | null, 
/**
 * When the cached entitlement stops being trusted. `None` for a perpetual
 * licence already verified.
 */
validUntil: string | null, 
/**
 * Running on a cached answer because the service was unreachable.
 * Surfaced rather than hidden: someone whose licence check is silently
 * failing should find out before the day it stops working.
 */
offline: boolean, 
/**
 * Written for a person, not a log.
 */
message: string | null, };
