// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Preferences } from "./Preferences";

/**
 * Preferences, plus a note if the stored file could not be used.
 *
 * The note travels in the payload rather than as an error because a broken
 * preferences file must not stop the app opening. It starts on defaults and
 * says what happened, instead of silently discarding someone's settings.
 */
export type LoadedPreferences = { preferences: Preferences, problem: string | null, 
/**
 * Black or white, whichever is legible on the chosen accent. Computed in
 * Rust and covered by tests, so a custom colour can never produce a button
 * whose label cannot be read.
 */
accentForeground: string, };
