// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a measurement came from. Shown in the UI so you can tell an
 * auto-detected value from one you measured yourself.
 */
export type MeasurementSource = "edid" | "manual" | "derived";
