// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeasurementSource } from "./MeasurementSource";
import type { Mm } from "./Mm";

/**
 * A length plus its provenance.
 */
export type Measurement = { mm: Mm, source: MeasurementSource, };
