// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A key the adapter wanted and the file does not have.
 *
 * Carries the section's real keys, because "your file does not have
 * SCREEN_WIDTH, it has these eleven things" is diagnosable and "key not found"
 * is not.
 */
export type MissingKey = { section: string, key: string, reason: string, sectionContains: Array<string>, };
