// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A length in millimetres. The only length unit that exists in the model.
 */
export type Mm = number;
