// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModuleStage } from "./ModuleStage";

export type ModuleStatus = { home: string, stage: ModuleStage, 
/**
 * Whether each piece is present, as checked on disk — never remembered.
 */
uvPresent: boolean, pythonPresent: boolean, envPresent: boolean, 
/**
 * Bytes under the home folder, so the tab can say what Remove reclaims.
 */
bytesOnDisk: number, 
/**
 * A line for the progress panel.
 */
message: string, error: string | null, 
/**
 * The last lines of the installer's output, newest last.
 */
log: Array<string>, 
/**
 * Whether an install or removal is running now.
 */
busy: boolean, };
