// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the module is, and what state it is in.
 */
export type ModuleStage = "not_installed" | "downloading_uv" | "installing_python" | "syncing_environment" | "ready" | "failed" | "removing";
