// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayMode } from "./DisplayMode";
import type { EdidIdentity } from "./EdidIdentity";
import type { PhysicalSize } from "./PhysicalSize";
import type { PixelRect } from "./PixelRect";
import type { Resolution } from "./Resolution";

export type MonitorInfo = { 
/**
 * CCD target device path. Stable while the cable stays in the same port.
 */
devicePath: string, 
/**
 * GDI name, e.g. `\\.\DISPLAY1`.
 */
gdiName: string, friendlyName: string, identity: EdidIdentity, nativeResolution: Resolution, currentMode: DisplayMode, 
/**
 * Position and size in virtual-desktop physical pixels. Signed: monitors
 * left of or above the primary have negative origins.
 */
bounds: PixelRect, isPrimary: boolean, 
/**
 * Windows scaling as a factor: 1.0 for 100%, 1.5 for 150%.
 */
dpiScale: number, 
/**
 * Physical visible area from EDID. `None` when the panel reports nothing
 * usable, which happens — the UI then asks for a manual measurement rather
 * than inventing a number.
 */
physicalSize: PhysicalSize | null, };
