// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdidIdentity } from "./EdidIdentity";

/**
 * How a rig screen is tied to a physically detected monitor.
 *
 * Note this binds by EDID identity, *not* by device path. The CCD device path
 * encodes the adapter and output, so moving a cable from DP-1 to DP-2 changes
 * it and would silently turn your left screen into your centre screen. The
 * monitor's own EDID identity is what actually survives a re-cable.
 */
export type MonitorBinding = { "kind": "edid" } & EdidIdentity | { "kind": "unbound" };
