// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MonitorPitch = { devicePath: string, 
/**
 * `None` when the monitor reports no physical size. The UI must ask for a
 * measurement rather than assume a pitch.
 */
pxPerMm: number | null, 
/**
 * True when this monitor's pitch differs from its left-hand neighbour's by
 * more than 10%. Where that holds, a bezel gap cannot be expressed in
 * pixels across the seam at all, and the app says so instead of returning
 * a number that is quietly wrong.
 */
differsFromNeighbour: boolean, };
