// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Deg } from "./Deg";
import type { Mm } from "./Mm";

export type MountingSpec = { 
/**
 * Yaw relative to the centre screen plane. Positive = angled inward,
 * toward the driver. A coplanar screen is 0.
 */
angle: Deg, 
/**
 * Extra physical space between this screen and its inboard neighbour,
 * *beyond* both adjacent bezels. Defined this way so that correcting a
 * bezel measurement does not silently change the mount gap.
 */
gap: Mm, 
/**
 * Positive = this screen's centre sits above the centre screen's centre.
 */
verticalOffset: Mm, 
/**
 * Eye to the centre of this screen's surface. `None` derives it from the
 * centre distance and the geometry, which is right for a normal mount.
 */
distanceOverride: Mm | null, 
/**
 * Reserved. Defaults to 0 and is not exposed in the v1 UI. Present in the
 * schema from the start because adding a field to a persisted format later
 * costs a migration, and reserving two f64 now costs nothing.
 */
pitch: Deg, 
/**
 * Reserved. See `pitch`.
 */
roll: Deg, };
