// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Everything observed about one device at one instant.
 */
export type Observation = { 
/**
 * Ground truth for "is this physically plugged in".
 */
hidPresent: boolean, 
/**
 * Whether DirectInput lists it — i.e. whether games can see it at all.
 */
dinputPresent: boolean, 
/**
 * `None` when the device declares no vendor requirement.
 */
vendorProcessRunning: boolean | null, 
/**
 * `None` when the device is not a vJoy target.
 */
vjoyFeederRunning: boolean | null, };
