// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WindowCandidate } from "./WindowCandidate";

/**
 * A window the user can pick from, for the test panel.
 */
export type OpenWindow = { candidate: WindowCandidate, 
/**
 * True when this one would survive the splash-and-tool-window filters.
 */
plausible: boolean, };
