// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bezel } from "./Bezel";
import type { Curvature } from "./Curvature";
import type { Measurement } from "./Measurement";
import type { Resolution } from "./Resolution";
import type { WidthMeasure } from "./WidthMeasure";

export type PanelSpec = { nativeResolution: Resolution, 
/**
 * The visible *image* area, not the outer chassis.
 */
visibleWidth: Measurement, visibleHeight: Measurement, 
/**
 * Whether `visible_width` was entered as arc (developed) or chord length.
 * Only meaningful when `curvature` is not `Flat`.
 */
widthMeasure: WidthMeasure, curvature: Curvature, bezel: Bezel, };
