// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A length parsed from whatever the user typed, rendered in every unit so the
 * UI can show normalised helper text under the field.
 */
export type ParsedLength = { mm: number, formattedMm: string, formattedCm: string, formattedInch: string, };
