// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A session that did not finish, for the recovery prompt.
 */
export type PendingSession = { profileName: string, startedAt: string, 
/**
 * Whether there is anything to put back. False means the session was
 * interrupted before it changed a thing, which is worth saying rather than
 * offering a recovery that would do nothing.
 */
hasConfigBackup: boolean, };
