// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceRef } from "./DeviceRef";
import type { Necessity } from "./Necessity";
import type { ProcessRequirement } from "./ProcessRequirement";
import type { VJoyRequirement } from "./VJoyRequirement";

export type PeripheralRequirement = { device: DeviceRef, necessity: Necessity, expectDinputSlot: number | null, expectInstanceGuid: string | null, vendorProcess: ProcessRequirement | null, vjoy: VJoyRequirement | null, };
