// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Mm } from "./Mm";

export type PhysicalSize = { width: Mm, height: Mm, 
/**
 * True when parsed from the EDID detailed timing descriptor (millimetre
 * precision) rather than EDID bytes 0x15/0x16 (whole centimetres, so a
 * 1193 mm panel reports 119 and quantises to +/-5 mm).
 */
millimetrePrecision: boolean, };
