// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A rectangle in virtual-desktop physical pixels. `x`/`y` are signed because
 * monitors left of or above the primary have negative coordinates.
 */
export type PixelRect = { x: number, y: number, width: number, height: number, };
