// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Appearance } from "./Appearance";
import type { LengthUnit } from "./LengthUnit";
import type { LibraryView } from "./LibraryView";
import type { TeamBranding } from "./TeamBranding";
import type { UpdatePolicy } from "./UpdatePolicy";

export type Preferences = { schemaVersion: number, 
/**
 * Display unit for lengths. A UI preference only — the model is always
 * millimetres.
 */
units: LengthUnit, appearance: Appearance, team: TeamBranding, 
/**
 * Start with Windows, minimised.
 *
 * Separate from `start_minimised` on purpose: most people want the app
 * there when they sit down without it taking the screen, and want it
 * front and centre when they open it themselves.
 */
runAtStartup: boolean, 
/**
 * Start minimised even when opened by hand.
 */
startMinimised: boolean, 
/**
 * What to do when a new version is available.
 */
updates: UpdatePolicy, 
/**
 * Whether the first-run wizard has been completed.
 *
 * `#[serde(default)]` so an existing preferences file loads as
 * not-yet-onboarded rather than failing to parse — which would lose every
 * other setting in it. The wizard is cheap to dismiss and impossible to
 * recover from a corrupt file.
 */
onboarded: boolean, 
/**
 * How the games library is drawn. A preference, not profile data — it
 * says how you like looking at your library, which has nothing to do with
 * any one game.
 */
library: LibraryView, 
/**
 * What the user calls each individual control, keyed by
 * `input_alias_key`. "Brake" and "Upshift" are what somebody thinks in;
 * "axis 2" and "button 7" are what the hardware says, and the test panel
 * is where those two get introduced to each other.
 */
inputAliases: { [key in string]?: string }, 
/**
 * What the user calls each device, keyed by `DeviceRef::alias_key`.
 *
 * Kept here rather than on a profile because a name for a pedal set is a
 * fact about the rig, not about one game — renaming it in front of
 * Assetto Corsa and finding it unchanged in iRacing would be absurd. The
 * user's name always wins over the catalog and over Windows: it is their
 * rig, and they are the one who has to recognise the row.
 */
deviceAliases: { [key in string]?: string }, };
