// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Appearance } from "./Appearance";
import type { LengthUnit } from "./LengthUnit";
import type { TeamBranding } from "./TeamBranding";
import type { UpdatePolicy } from "./UpdatePolicy";

export type Preferences = { schemaVersion: number, 
/**
 * Display unit for lengths. A UI preference only — the model is always
 * millimetres.
 */
units: LengthUnit, appearance: Appearance, team: TeamBranding, 
/**
 * Start with Windows, minimised.
 *
 * Separate from `start_minimised` on purpose: most people want the app
 * there when they sit down without it taking the screen, and want it
 * front and centre when they open it themselves.
 */
runAtStartup: boolean, 
/**
 * Start minimised even when opened by hand.
 */
startMinimised: boolean, 
/**
 * What to do when a new version is available.
 */
updates: UpdatePolicy, 
/**
 * Whether the first-run wizard has been completed.
 *
 * `#[serde(default)]` so an existing preferences file loads as
 * not-yet-onboarded rather than failing to parse — which would lose every
 * other setting in it. The wizard is cheap to dismiss and impossible to
 * recover from a corrupt file.
 */
onboarded: boolean, };
