// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Appearance } from "./Appearance";
import type { LengthUnit } from "./LengthUnit";
import type { TeamBranding } from "./TeamBranding";

export type Preferences = { schemaVersion: number, 
/**
 * Display unit for lengths. A UI preference only — the model is always
 * millimetres.
 */
units: LengthUnit, appearance: Appearance, team: TeamBranding, };
