// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Profile } from "./Profile";

/**
 * A profile plus what is true about it *right now*.
 *
 * Kept separate from `Profile` because installed-ness is not a property of the
 * profile — it is a property of this machine at this moment, and writing it
 * into the saved file would mean a profile that lies after an uninstall.
 */
export type ProfileCard = { profile: Profile, 
/**
 * Whether the game is on this machine now.
 */
installed: boolean, 
/**
 * Cover art as a data URI, or null when there is none to show.
 *
 * Inlined rather than served over a URL: it keeps the asset protocol out
 * of the app's attack surface entirely, and the images are small.
 */
art: string | null, 
/**
 * Where it lives, for the card. `None` once the folder has gone.
 */
installPath: string | null, platform: string, };
