// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceRef } from "./DeviceRef";
import type { WindowTarget } from "./WindowTarget";

export type ReadinessGate = { "kind": "immediate" } | { "kind": "delay", ms: bigint, } | { "kind": "process_exists", exe: string, } | { "kind": "input_idle", timeoutMs: bigint, } | { "kind": "window_exists", target: WindowTarget, } | { "kind": "named_mutex", name: string, } | { "kind": "named_event", name: string, } | { "kind": "tcp_port", host: string, port: number, } | { "kind": "file_appears", path: string, } | { "kind": "peripheral_connected", device: DeviceRef, } | { "kind": "all", gates: Array<ReadinessGate>, } | { "kind": "any", gates: Array<ReadinessGate>, };
