// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What pressing Reconnect produced, as the UI sees it.
 *
 * Only the two outcomes that are not failures. Everything that went wrong is
 * an error with a sentence attached, because each failure has a different
 * thing the person should do next and a status alone cannot say which.
 */
export type ReconnectOutcome = "restarted" | "declined";
