// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PixelRect } from "./PixelRect";

export type RectSource = { "kind": "from_geometry" } | { "kind": "explicit", rect: PixelRect, };
