// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Remedy = { "kind": "relaunch_elevated" } | { "kind": "retry" } | { "kind": "open_settings", section: string, };
