// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScreenId } from "./ScreenId";

export type ResidualInfo = { id: ScreenId, maxErrorDeg: number, rmsErrorDeg: number, };
