// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A size in physical pixels. Never DIPs — see docs/design/0001-stack.md.
 */
export type Resolution = { width: number, height: number, };
