// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RigBinding = { rigId: string, computedAgainstRevision: bigint, 
/**
 * Exactly the numbers last written to this game, keyed by a stable field
 * name (`"center.h_fov_deg"`, `"bezel.inner_px"`). Stored so the
 * recompute-and-propagate diff is exact and works offline, with no need to
 * reconstruct the previous rig. A flat name->number map rather than free
 * JSON so the diff is mechanical and the TypeScript type is honest.
 */
derivedSnapshot: { [key in string]?: number }, };
