// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LengthUnit } from "./LengthUnit";
import type { ScreenSpec } from "./ScreenSpec";
import type { Seating } from "./Seating";

export type RigModel = { schemaVersion: number, id: string, 
/**
 * Incremented on every save. Profiles record the revision they were last
 * computed against, which is what drives recompute-and-propagate.
 */
revision: bigint, name: string, 
/**
 * ISO-8601. A string rather than a timestamp type so the TypeScript
 * binding is unambiguous and no date library is implied.
 */
updatedAt: string, 
/**
 * UI preference only. Never the source of truth for any stored value.
 */
unitsPreference: LengthUnit, seating: Seating, 
/**
 * Ordered left to right as physically arranged.
 */
screens: Array<ScreenSpec>, };
