// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RigWarningInfo } from "./RigWarningInfo";
import type { ScreenSolutionInfo } from "./ScreenSolutionInfo";

/**
 * A solved rig, flattened for the UI.
 *
 * `tp-geometry` owns the real types; these are the wire shapes. Keeping them
 * here rather than deriving serde in the geometry crate keeps that crate about
 * mathematics, and keeps every TypeScript binding generated from one place.
 */
export type RigSolutionInfo = { screens: Array<ScreenSolutionInfo>, 
/**
 * Outer edge to outer edge, bezel gaps included.
 */
totalCoverageDeg: number, 
/**
 * Sum of the per-screen spans, gaps excluded.
 */
visibleCoverageDeg: number, warnings: Array<RigWarningInfo>, };
