// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScreenId } from "./ScreenId";

export type RigWarningInfo = { 
/**
 * A stable slug, for styling and for tests. The UI renders `message`.
 */
kind: string, 
/**
 * One sentence saying what is wrong and what it means, written for a
 * person rather than a log.
 */
message: string, screenId: ScreenId | null, };
