// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A program running right now, as something the user could pick.
 */
export type RunningApp = { 
/**
 * The executable's file name, e.g. `SimHub.exe`. This is what a
 * `ProcessExists` gate matches on.
 */
exe: string, 
/**
 * The full path, which is what actually gets started.
 */
exePath: string, 
/**
 * A tidied name for the list: the file name without its extension.
 */
label: string, };
