// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GapInfo } from "./GapInfo";
import type { ScreenId } from "./ScreenId";
import type { ScreenRole } from "./ScreenRole";
import type { SpanInfo } from "./SpanInfo";

export type ScreenSolutionInfo = { id: ScreenId, role: ScreenRole, distanceMm: number, 
/**
 * What a flat-projecting sim should be told. For a curved panel this is
 * the chord width at the chord-plane distance, not the arc.
 */
flatWidthMm: number, flatHeightMm: number, 
/**
 * The symmetric equivalent: `|left| + |right|`.
 */
hFovDeg: number, vFovDeg: number, 
/**
 * The asymmetric truth. Any yawed screen or lateral seating offset makes
 * left and right differ, and a single half-angle would hide it.
 */
span: SpanInfo, pxPerDegH: number, pxPerDegV: number, innerGap: GapInfo | null, curvatureErrorDeg: number | null, 
/**
 * Centre of the visible surface in the eye frame, millimetres.
 * `[x right, y up, z forward]`. The schematic draws straight from this.
 */
centre: [number, number, number], 
/**
 * Visible corners in the same frame: inboard-bottom, inboard-top,
 * outboard-bottom, outboard-top.
 */
corners: [[number, number, number], [number, number, number], [number, number, number], [number, number, number]], };
