// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonitorBinding } from "./MonitorBinding";
import type { MountingSpec } from "./MountingSpec";
import type { PanelSpec } from "./PanelSpec";
import type { ScreenId } from "./ScreenId";
import type { ScreenRole } from "./ScreenRole";

export type ScreenSpec = { id: ScreenId, role: ScreenRole, binding: MonitorBinding, panel: PanelSpec, mounting: MountingSpec, };
