// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Mm } from "./Mm";

/**
 * Where the driver's eyes are. The origin of the whole coordinate system.
 */
export type Seating = { 
/**
 * Eye to the *nearest point* of the centre screen's visible surface. On a
 * curved panel that is the middle of the curve; the chord-plane distance
 * is derived from it, not measured.
 */
eyeToCenter: Mm, 
/**
 * Positive = eye above the centre screen's vertical centre.
 */
eyeHeightOffset: Mm, 
/**
 * Positive = eye to the right of the centre screen's horizontal centre.
 */
lateralOffset: Mm, };
