// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceState } from "./ServiceState";

/**
 * What the frontend needs to talk to the service, and whether it can.
 */
export type ServiceInfo = { state: ServiceState, 
/**
 * `http://127.0.0.1:<port>` while the service is up.
 */
baseUrl: string | null, 
/**
 * The per-session token every request must carry.
 */
token: string | null, pid: number | null, message: string, 
/**
 * Whether generation is paused because a session is running.
 */
pausedForRace: boolean, };
