// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PixelRect } from "./PixelRect";
import type { SpanFit } from "./SpanFit";

/**
 * How a game session uses the rig. Derived per profile, never typed in.
 */
export type SessionMode = { "kind": "center_only" } | { "kind": "full_span", fit: SpanFit, } | { "kind": "custom_rect", rect: PixelRect, };
