// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayMode } from "./DisplayMode";

export type SnapshotEntry = { devicePath: string, active: boolean, mode: DisplayMode, position: [number, number], isPrimary: boolean, };
