// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How to reconcile unequal panel heights when spanning.
 */
export type SpanFit = "letterbox" | "crop" | "stretch";
