// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpanInfo = { leftDeg: number, rightDeg: number, bottomDeg: number, topDeg: number, 
/**
 * How far off-centre the screen sits. Above about 1 degree the UI shows
 * the asymmetry rather than only the symmetric equivalent.
 */
asymmetryDeg: number, };
