// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the app starts with Windows, as the registry actually reports it.
 */
export type StartupState = { enabled: boolean, 
/**
 * The registered command no longer points at this executable — the app has
 * been moved or reinstalled elsewhere, leaving an entry that launches
 * nothing. Surfaced rather than silently repaired: quietly rewriting a
 * registry value the user did not ask about is not this app's business.
 */
stale: boolean, };
