// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionTaken } from "./ActionTaken";
import type { FixAction } from "./FixAction";
import type { Phase } from "./Phase";
import type { Severity } from "./Severity";
import type { StepId } from "./StepId";
import type { StepStatus } from "./StepStatus";

/**
 * Wire shape for the UI: one row of the preflight checklist.
 */
export type StepView = { id: StepId, label: string, phase: Phase, severity: Severity, status: StepStatus, detail: string, 
/**
 * f64 rather than u64: a u64 crosses into JavaScript as `bigint`, which
 * cannot be divided by a number without a cast at every call site. Elapsed
 * milliseconds never approach the precision limit.
 */
elapsedMs: number | null, 
/**
 * What the app actually did, so the row cannot claim credit it has not
 * earned — "Already running" is derived from this, never written by hand.
 */
actionTaken: ActionTaken, canRetry: boolean, 
/**
 * The profile's own idea of how to fix this step, carried through so the
 * row can offer a button rather than leaving a red line with no way out.
 */
fix: FixAction | null, };
