// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionTaken } from "./ActionTaken";
import type { Phase } from "./Phase";
import type { Severity } from "./Severity";
import type { StepId } from "./StepId";
import type { StepStatus } from "./StepStatus";

/**
 * Wire shape for the UI: one row of the preflight checklist.
 */
export type StepView = { id: StepId, label: string, phase: Phase, severity: Severity, status: StepStatus, detail: string, elapsedMs: bigint | null, 
/**
 * What the app actually did, so the row cannot claim credit it has not
 * earned — "Already running" is derived from this, never written by hand.
 */
actionTaken: ActionTaken, canRetry: boolean, };
