// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FixAction } from "./FixAction";
import type { Phase } from "./Phase";
import type { ReadinessGate } from "./ReadinessGate";
import type { Severity } from "./Severity";
import type { StepAction } from "./StepAction";
import type { StepId } from "./StepId";

export type StepSpec = { id: StepId, label: string, phase: Phase, 
/**
 * Steps with no dependency between them run in parallel. A preflight that
 * insists on being sequential is a preflight nobody uses.
 */
dependsOn: Array<StepId>, action: StepAction, gate: ReadinessGate, timeoutMs: bigint, severity: Severity, fix: FixAction | null, 
/**
 * Minimum time a row stays visible, so an instant pass is readable rather
 * than a flicker. Never used to pad the total run.
 */
minVisibleMs: bigint, };
