// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceRef } from "./DeviceRef";

export type StepAction = { "kind": "ensure_process", exePath: string, args: Array<string>, } | { "kind": "start_process", exePath: string, args: Array<string>, } | { "kind": "check_peripheral", device: DeviceRef, } | { "kind": "check_display_topology" } | { "kind": "apply_display_snapshot", snapshotId: string, } | { "kind": "check_game_installed" } | { "kind": "check_config_writable" } | { "kind": "check_not_already_running" } | { "kind": "apply_adapter", adapterId: string, } | { "kind": "launch_game" } | { "kind": "apply_window_geometry" } | { "kind": "restore_configs" } | { "kind": "restore_display" } | { "kind": "close_utilities" };
