// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionTaken } from "./ActionTaken";
import type { StepId } from "./StepId";
import type { StepStatus } from "./StepStatus";

export type StepOutcome = { id: StepId, status: StepStatus, actionTaken: ActionTaken, 
/**
 * The one-line live detail shown on the row.
 */
detail: string, startedAt: string | null, finishedAt: string | null, elapsedMs: bigint | null, error: string | null, };
