// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TeamLogo = { 
/**
 * The image inlined as a `data:` URI.
 *
 * Inlined rather than referenced by path so that preferences.json is
 * self-contained: it survives being copied to another machine, and the app
 * never has to reason about a logo file that has been moved or deleted.
 */
dataUri: string, 
/**
 * The original filename, so the settings screen can say what is loaded.
 */
fileName: string, };
