// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TeamLogo } from "./TeamLogo";

export type TeamBranding = { 
/**
 * Shown beside the logo in the title bar. Empty means no name.
 */
name: string | null, logo: TeamLogo | null, };
