// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TeardownPolicy = { restoreDisplay: boolean, restoreConfigs: boolean, closeUtilities: boolean, 
/**
 * Whether utilities stay running when a preflight is cancelled part-way.
 */
keepUtilitiesOnCancel: boolean, };
