// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the app is entitled to do.
 *
 * No vendor is named anywhere in this project: a merchant-of-record handles
 * the money and a licence service handles the keys, and neither is chosen. The
 * types here define the shape of the question so there is exactly one place to
 * answer it.
 */
export type Tier = "unlicensed" | "licensed";
