// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TopologyChange } from "./TopologyChange";
import type { TopologyProblem } from "./TopologyProblem";

/**
 * Everything the confirm screen needs: what changes, and what is wrong with it.
 */
export type TopologyPreview = { changes: Array<TopologyChange>, problems: Array<TopologyProblem>, };
