// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Resolution } from "./Resolution";

/**
 * One thing a plan would change, in the words the UI shows.
 */
export type TopologyChange = { "kind": "resolution", monitor: string, from: Resolution, to: Resolution, } | { "kind": "refresh_rate", monitor: string, fromHz: number, toHz: number, } | { "kind": "position", monitor: string, from: [number, number], to: [number, number], } | { "kind": "primary", from: string | null, to: string, } | { "kind": "activated", monitor: string, } | { "kind": "deactivated", monitor: string, };
