// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SnapshotEntry } from "./SnapshotEntry";

/**
 * A complete topology snapshot: enough to put the desktop back exactly as it
 * was. Captured before any change and restorable by the panic hotkey.
 */
export type TopologySnapshot = { id: string, capturedAt: string, monitors: Array<SnapshotEntry>, };
