// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProblemSeverity } from "./ProblemSeverity";

export type TopologyProblem = { severity: ProblemSeverity, message: string, };
