// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateOutcome = { "kind": "no_key" } | { "kind": "nothing_published" } | { "kind": "up_to_date" } | { "kind": "available", version: string, 
/**
 * The release notes, as written on the release.
 */
notes: string | null, publishedAt: string | null, } | { "kind": "unreachable", message: string, };
