// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an install has got to.
 *
 * An update is the one operation that ends with the app disappearing and
 * coming back, so a button that greys out and says nothing for thirty seconds
 * reads as a crash. Every phase is published, including the failures — which
 * used to be swallowed entirely by the callers.
 */
export type UpdateStage = { "kind": "checking" } | { "kind": "downloading", downloaded: number, total: number | null, } | { "kind": "installing" } | { "kind": "restarting" } | { "kind": "failed", message: string, };
