// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateOutcome } from "./UpdateOutcome";

/**
 * What a check found.
 *
 * Every outcome is named. The alternative — a pair of booleans and an error —
 * forced the UI to infer, and it inferred wrong: a repository with no releases
 * in it yet reported "could not reach the update service", which describes a
 * broken network rather than a product that has not shipped.
 */
export type UpdateInfo = { currentVersion: string, outcome: UpdateOutcome, };
