// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a check found.
 */
export type UpdateInfo = { available: boolean, currentVersion: string, 
/**
 * `None` when nothing newer was found.
 */
newVersion: string | null, 
/**
 * The release notes, as written on the release.
 */
notes: string | null, publishedAt: string | null, 
/**
 * False when this build has no update endpoint configured — a private
 * build, or one made before the signing key existed. Reported rather than
 * shown as "up to date", which would be a claim nothing checked.
 */
configured: boolean, };
