// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReadinessGate } from "./ReadinessGate";

/**
 * A utility the profile wants running before a session.
 */
export type UtilitySpec = { label: string, exePath: string, args: Array<string>, 
/**
 * How to know it is *ready*, not merely running. This is the field that
 * replaces the hardcoded sleep every other launcher relies on.
 */
readyWhen: ReadinessGate, timeoutMs: number, 
/**
 * Whether failing to start it blocks the launch.
 */
required: boolean, 
/**
 * Labels of utilities that must be ready first. Names rather than ids, so
 * reordering the list does not break the chain.
 */
after: Array<string>, };
