// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ValueChange = { section: string, key: string, 
/**
 * What the file says now.
 */
from: string, to: string, because: string, 
/**
 * Already correct. Shown but not counted as a change, so a second apply
 * visibly does nothing rather than looking like it rewrote the file.
 */
unchanged: boolean, };
