// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VJoyStatus } from "./VJoyStatus";

export type VJoyInfo = { 
/**
 * vJoy device id, 1..=16.
 */
deviceId: number, driverVersion: string | null, interfaceVersion: string | null, 
/**
 * vJoy reports its own status; a device can exist but be unowned, which
 * means nothing is feeding it and its axes read as dead centre.
 */
status: VJoyStatus, 
/**
 * Process expected to be feeding this device.
 */
feederProcess: string | null, feederRunning: boolean, };
