// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessRequirement } from "./ProcessRequirement";

export type VJoyRequirement = { deviceId: number, feeder: ProcessRequirement | null, };
