// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Voice Lab settings. Part of `Preferences`, and every field has a default
 * so an existing preferences file loads unchanged.
 */
export type VoiceLabSettings = { 
/**
 * The user asked for the module; the tab should offer to build it and
 * start the service when opened.
 */
enabled: boolean, 
/**
 * Where the module lives. `None` means the default under `%LOCALAPPDATA%`.
 */
home: string | null, 
/**
 * CrewChief's sounds folder, when the default is not where it is.
 */
soundsFolder: string | null, 
/**
 * Baked into phrases that address the driver.
 */
yourName: string | null, 
/**
 * How long the service may sit idle before the app stops it.
 */
idleStopMinutes: number, 
/**
 * The engine new packs use.
 */
engine: string, 
/**
 * GPU workers. `None` sizes the pool from free VRAM.
 */
workers: number | null, 
/**
 * The optional pit-radio effect, per pack.
 */
radioEffect: boolean, 
/**
 * Clips per phrase in a full pack.
 */
variants: number, };
