// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpuInfo } from "./GpuInfo";

/**
 * What the Voice Lab needs and whether this machine has it.
 */
export type VoiceLabRequirements = { ok: boolean, 
/**
 * The adapter that would be used, if any qualifies — else the best there is.
 */
gpu: GpuInfo | null, 
/**
 * Every adapter seen, for the requirements screen.
 */
gpus: Array<GpuInfo>, minVramMb: number, minDriver: string, 
/**
 * Each unmet requirement, as a sentence.
 */
problems: Array<string>, };
