// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WatchdogPolicy = { 
/**
 * Re-apply N times over `reapply_window_ms` after launch, because many
 * sims reset their own window when the render device initialises.
 */
reapplyCount: number, reapplyWindowMs: number, 
/**
 * Ongoing drift correction. `None` disables it.
 */
driftCheckIntervalMs: number | null, stopAfterStableMs: number | null, };
