// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RectMeans } from "./RectMeans";
import type { RectSource } from "./RectSource";
import type { WatchdogPolicy } from "./WatchdogPolicy";
import type { WindowTarget } from "./WindowTarget";

export type WindowPlan = { target: WindowTarget, rect: RectSource, 
/**
 * Required, with no default. A rectangle that does not say whether it is
 * the client area or the outer window is ambiguous by exactly the border
 * width, and a few pixels of horizontal error puts the horizon seam in the
 * wrong place on every screen of a triple.
 */
rectMeans: RectMeans, borderless: boolean, alwaysOnTop: boolean, hideTaskbar: boolean, watchdog: WatchdogPolicy, };
