// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PixelRect } from "./PixelRect";

/**
 * One top-level window, as enumeration found it.
 */
export type WindowCandidate = { 
/**
 * The HWND as an integer, so this type needs no Win32 dependency.
 */
hwnd: bigint, pid: number, exeName: string | null, className: string, title: string, rect: PixelRect, style: number, exStyle: number, visible: boolean, };
