// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PixelRect } from "./PixelRect";

/**
 * The outcome of placing a window, after it has been read back.
 */
export type WindowResult = { hwnd: string, title: string, 
/**
 * What identified this window as the game, so a wrong pick is diagnosable.
 */
matchedBy: Array<string>, requested: PixelRect, 
/**
 * Read back after the change, never assumed from a return value.
 */
actualOuter: PixelRect, actualClient: PixelRect, borderless: boolean, 
/**
 * True while the watchdog is putting the window back when the game moves it.
 */
watching: boolean, };
