// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WindowTarget = { exeName: string | null, windowClass: string | null, titleRegex: string | null, 
/**
 * Splash and loader filter. Never "the first window that appears".
 */
minSize: [number, number], requireVisible: boolean, timeoutMs: bigint, };
