// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WindowCandidate } from "./WindowCandidate";

/**
 * Why a particular window was chosen, so a failure to find one can say what
 * it did look at rather than only that it failed.
 */
export type WindowMatch = { window: WindowCandidate, matchedBy: Array<string>, };
