// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Derived } from "./Derived";

/**
 * One setting in one file.
 */
export type Write = { 
/**
 * INI section, or empty for XML.
 */
section: string, 
/**
 * INI key, or XML element name.
 */
key: string, 
/**
 * XML attribute, when the value is an attribute rather than element text.
 */
attribute: string | null, value: Derived, 
/**
 * Why, in the user's terms. `{}` is replaced with the value.
 */
because: string, 
/**
 * Only write this when the session spans every screen.
 */
tripleOnly: boolean, };
