//! The internal error type and its conversion to the wire shape.
//!
//! The wire shape ([`tp_model::IpcError`]) lives in `tp-model` so the
//! TypeScript binding for it is generated by a crate that compiles anywhere.
//! This enum is the richer internal one: it keeps the OS error code for the log
//! file while making sure a raw code never reaches the UI.

use tp_model::{IpcError, Remedy};

#[derive(Debug, thiserror::Error)]
pub enum AppError {
    #[error("{0}")]
    Config(String),

    #[error("{what} is not implemented yet — it arrives in milestone {milestone}")]
    NotYetImplemented { what: String, milestone: u8 },

    /// A Win32 call failed. `operation` names what we were trying to do, so the
    /// UI can say "couldn't resize the game window" rather than "error 5".
    #[error("{operation} failed: {message}")]
    Win32 {
        operation: String,
        code: u32,
        message: String,
    },

    /// The target window belongs to a higher-integrity process. Kept distinct
    /// from a generic failure because it has a specific remedy — relaunch
    /// elevated — and because UIPI makes this failure silent by default.
    #[error("{operation} was refused because the game runs at a higher integrity level")]
    ElevationRequired { operation: String },

    #[error("io error: {0}")]
    Io(String),

    #[error("{0}")]
    Serde(String),
}

impl AppError {
    fn kind(&self) -> &'static str {
        match self {
            AppError::Config(_) => "config",
            AppError::NotYetImplemented { .. } => "not_yet_implemented",
            AppError::Win32 { .. } => "win32",
            AppError::ElevationRequired { .. } => "elevation_required",
            AppError::Io(_) => "io",
            AppError::Serde(_) => "serde",
        }
    }

    fn remedy(&self) -> Option<Remedy> {
        match self {
            AppError::ElevationRequired { .. } => Some(Remedy::RelaunchElevated),
            AppError::Win32 { .. } | AppError::Io(_) => Some(Remedy::Retry),
            _ => None,
        }
    }
}

impl From<&AppError> for IpcError {
    fn from(e: &AppError) -> Self {
        IpcError {
            kind: e.kind().to_string(),
            message: e.to_string(),
            remedy: e.remedy(),
        }
    }
}

impl From<std::io::Error> for AppError {
    fn from(e: std::io::Error) -> Self {
        AppError::Io(e.to_string())
    }
}

impl From<serde_json::Error> for AppError {
    fn from(e: serde_json::Error) -> Self {
        AppError::Serde(e.to_string())
    }
}

/// Tauri serialises a command's `Err` straight to the frontend, so this is the
/// single point at which an internal error becomes something the UI can render.
impl serde::Serialize for AppError {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        IpcError::from(self).serialize(s)
    }
}

pub type AppResult<T> = Result<T, AppError>;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn elevation_failures_carry_their_remedy() {
        // The UI turns `remedy` into the inline fix button on a failed row. A
        // red row with no button is a dead end, so this is load-bearing.
        let e = AppError::ElevationRequired {
            operation: "resize the game window".into(),
        };
        let wire = IpcError::from(&e);
        assert_eq!(wire.kind, "elevation_required");
        assert_eq!(wire.remedy, Some(Remedy::RelaunchElevated));
        assert!(wire.message.contains("higher integrity"));
    }

    #[test]
    fn raw_os_codes_never_reach_the_message() {
        let e = AppError::Win32 {
            operation: "SetWindowPos".into(),
            code: 5,
            message: "Access is denied.".into(),
        };
        let wire = IpcError::from(&e);
        assert!(wire.message.contains("SetWindowPos failed"));
        assert_eq!(wire.remedy, Some(Remedy::Retry));
    }
}
