//! Updating the app in place.
//!
//! Releases are hosted on GitHub. The updater fetches a small JSON manifest,
//! compares versions, and — if asked — downloads the new installer and runs it.
//!
//! ## Two different signatures, and conflating them is expensive
//!
//! * The **updater signature** is a minisign keypair generated by the owner.
//!   Its public half is compiled into the app; its private half never leaves
//!   their hands. It proves an update came from them, and is what stops a
//!   compromised release host — or anyone who can intercept the download —
//!   pushing arbitrary code onto every customer's machine. It is free.
//! * The **code-signing certificate** is bought from a certificate authority
//!   and is what stops Windows SmartScreen warning on install. It is a
//!   different key, a different mechanism, and solves a different problem.
//!
//! An app can have either without the other. This handles the first; the second
//! is a purchase, and `docs/RELEASING.md` says what to buy.
//!
//! ## Settings survive
//!
//! Nothing here touches `%APPDATA%\Team Principal`. Rigs, profiles, snapshots,
//! backups and preferences all live there and the installer only replaces
//! program files — which is why an update keeps everything and a reinstall
//! does too.

use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};

use tauri::{AppHandle, Emitter};
use tauri_plugin_updater::UpdaterExt;
use tp_model::{UpdateInfo, UpdateStage};

use crate::error::{AppError, AppResult};

/// Where an install has got to. The UI subscribes rather than guessing from a
/// disabled button.
pub const STAGE_EVENT: &str = "updates://stage";

fn stage(app: &AppHandle, stage: UpdateStage) {
    if let Err(e) = app.emit(STAGE_EVENT, &stage) {
        tracing::debug!(error = %e, "could not publish an update stage");
    }
}

/// Set while an install is running.
///
/// Two things can start one — the strip at the top of the app and the Settings
/// screen — and an automatic install starts on its own. Two downloads racing
/// each other to replace the same binary is not a state worth having, so the
/// second one is refused with something to read rather than allowed to
/// interleave.
static INSTALLING: AtomicBool = AtomicBool::new(false);

/// The placeholder that ships when no signing key has been configured.
///
/// A build carrying this cannot verify anything, so it says so rather than
/// checking and reporting "up to date" — which would be a claim nothing made.
const UNCONFIGURED: &str = "UNCONFIGURED";

fn version() -> String {
    env!("CARGO_PKG_VERSION").to_string()
}

/// Is this build able to check for updates at all?
pub fn is_configured(app: &AppHandle) -> bool {
    app.config()
        .plugins
        .0
        .get("updater")
        .and_then(|v| v.get("pubkey"))
        .and_then(|v| v.as_str())
        .is_some_and(|key| key != UNCONFIGURED && !key.is_empty())
}

/// Ask the endpoint what the latest version is. Downloads nothing.
pub async fn check(app: &AppHandle) -> AppResult<UpdateInfo> {
    if !is_configured(app) {
        return Ok(UpdateInfo {
            available: false,
            current_version: version(),
            new_version: None,
            notes: None,
            published_at: None,
            configured: false,
        });
    }

    let updater = app
        .updater()
        .map_err(|e| AppError::Config(format!("the updater could not start: {e}")))?;

    match updater.check().await {
        Ok(Some(update)) => Ok(UpdateInfo {
            available: true,
            current_version: update.current_version.clone(),
            new_version: Some(update.version.clone()),
            notes: update.body.clone(),
            published_at: update.date.map(|d| d.to_string()),
            configured: true,
        }),
        Ok(None) => Ok(UpdateInfo {
            available: false,
            current_version: version(),
            new_version: None,
            notes: None,
            published_at: None,
            configured: true,
        }),
        // Being offline is the normal case for a rig in a garage, and it is not
        // a failure of this app. The message says which it was.
        Err(e) => Err(AppError::Config(format!(
            "could not reach the update service: {e}"
        ))),
    }
}

/// Download and install the update, then restart.
///
/// Refuses while a session is in flight. An update that restarts the launcher
/// out from under a running race would be unforgivable, and the marker that
/// says a session is live is already on disk for exactly this kind of question.
pub async fn install(app: &AppHandle) -> AppResult<()> {
    if INSTALLING.swap(true, Ordering::SeqCst) {
        return Err(AppError::Config("an update is already installing".into()));
    }

    let outcome = install_once(app).await;
    // Only reached when the install did *not* restart the app.
    INSTALLING.store(false, Ordering::SeqCst);
    outcome
}

async fn install_once(app: &AppHandle) -> AppResult<()> {
    match run_install(app).await {
        Ok(()) => Ok(()),
        Err(e) => {
            // Both the banner and Settings can start this, and both used to
            // drop the error on the floor. Publishing it means a refusal is
            // visible wherever the install was started from.
            stage(
                app,
                UpdateStage::Failed {
                    message: e.to_string(),
                },
            );
            Err(e)
        }
    }
}

async fn run_install(app: &AppHandle) -> AppResult<()> {
    if let Some(session) = crate::session::pending() {
        return Err(AppError::Config(format!(
            "{} is mid-session. Finish the race and try again — restarting the \
             app now would tear down what it started.",
            session.profile_name
        )));
    }

    stage(app, UpdateStage::Checking);

    let updater = app
        .updater()
        .map_err(|e| AppError::Config(format!("the updater could not start: {e}")))?;
    let Some(update) = updater
        .check()
        .await
        .map_err(|e| AppError::Config(format!("could not reach the update service: {e}")))?
    else {
        return Err(AppError::Config("there is no update to install".into()));
    };

    tracing::info!(from = %update.current_version, to = %update.version, "installing an update");

    // Progress arrives per chunk, which is far more often than a screen can
    // use. The running total is kept here and published as it changes; the UI
    // throttles nothing because there is nothing left to throttle.
    let downloaded = AtomicU64::new(0);

    // The signature is verified inside this call, against the public key
    // compiled into this binary. An update that does not verify is refused
    // before a single byte of it is run.
    update
        .download_and_install(
            |chunk, total| {
                let so_far = downloaded.fetch_add(chunk as u64, Ordering::Relaxed) + chunk as u64;
                stage(
                    app,
                    UpdateStage::Downloading {
                        downloaded: so_far,
                        total,
                    },
                );
            },
            || stage(app, UpdateStage::Installing),
        )
        .await
        .map_err(|e| AppError::Config(format!("the update could not be installed: {e}")))?;

    tracing::info!("update installed; restarting");
    stage(app, UpdateStage::Restarting);
    app.restart();
}
