/**
 * The typed IPC client. This is the *only* place the frontend talks to Rust.
 *
 * Payload types come from `src/bindings/`, which is generated by ts-rs from the
 * Rust models — never hand-edited. The thin wrappers below exist so command
 * names appear exactly once in the frontend; `scripts/check-ipc.mjs` asserts
 * that every `#[tauri::command]` in Rust has a wrapper here and vice versa, so
 * a renamed or removed command fails CI instead of failing at runtime.
 */
import { invoke } from "@tauri-apps/api/core";
import { listen, type UnlistenFn } from "@tauri-apps/api/event";

import type { AccentPreset } from "./bindings/AccentPreset";
import type { AppInfo } from "./bindings/AppInfo";
import type { AdapterInfo } from "./bindings/AdapterInfo";
import type { AdapterPreview } from "./bindings/AdapterPreview";
import type { ConfigInspection } from "./bindings/ConfigInspection";
import type { AppliedAdapterInfo } from "./bindings/AppliedAdapterInfo";
import type { AvailableModes } from "./bindings/AvailableModes";
import type { BackupInfo } from "./bindings/BackupInfo";
import type { CaptureResult } from "./bindings/CaptureResult";
import type { CapturedLayout } from "./bindings/CapturedLayout";
import type { Confidence } from "./bindings/Confidence";
import type { FileDiff } from "./bindings/FileDiff";
import type { MissingKey } from "./bindings/MissingKey";
import type { ValueChange } from "./bindings/ValueChange";
import type { AxisReading } from "./bindings/AxisReading";
import type { ConfirmOutcome } from "./bindings/ConfirmOutcome";
import type { ConfirmState } from "./bindings/ConfirmState";
import type { DisplayMode } from "./bindings/DisplayMode";
import type { HotkeyInfo } from "./bindings/HotkeyInfo";
import type { SnapshotEntry } from "./bindings/SnapshotEntry";
import type { TopologyChange } from "./bindings/TopologyChange";
import type { TopologyPreview } from "./bindings/TopologyPreview";
import type { TopologyProblem } from "./bindings/TopologyProblem";
import type { TopologySnapshot } from "./bindings/TopologySnapshot";
import type { BestFitInfo } from "./bindings/BestFitInfo";
import type { CurveResult } from "./bindings/CurveResult";
import type { DesktopLayoutInfo } from "./bindings/DesktopLayoutInfo";
import type { DetectedDevice } from "./bindings/DetectedDevice";
import type { GlassLevel } from "./bindings/GlassLevel";
import type { InputFrame } from "./bindings/InputFrame";
import type { InputStatus } from "./bindings/InputStatus";
import type { LicenceState } from "./bindings/LicenceState";
import type { Tier } from "./bindings/Tier";
import type { FixAction } from "./bindings/FixAction";
import type { InstalledGameInfo } from "./bindings/InstalledGameInfo";
import type { Necessity } from "./bindings/Necessity";
import type { PendingSession } from "./bindings/PendingSession";
import type { PeripheralRequirement } from "./bindings/PeripheralRequirement";
import type { Platform } from "./bindings/Platform";
import type { Profile } from "./bindings/Profile";
import type { ProfileCard } from "./bindings/ProfileCard";
import type { ReadinessGate } from "./bindings/ReadinessGate";
import type { Severity } from "./bindings/Severity";
import type { StepStatus } from "./bindings/StepStatus";
import type { UtilitySpec } from "./bindings/UtilitySpec";
import type { ReadyState } from "./bindings/ReadyState";
import type { StepView } from "./bindings/StepView";
import type { OpenWindow } from "./bindings/OpenWindow";
import type { RectMeans } from "./bindings/RectMeans";
import type { WindowResult } from "./bindings/WindowResult";
import type { LoadedPreferences } from "./bindings/LoadedPreferences";
import type { Preferences } from "./bindings/Preferences";
import type { RigModel } from "./bindings/RigModel";
import type { RigSolutionInfo } from "./bindings/RigSolutionInfo";
import type { RigWarningInfo } from "./bindings/RigWarningInfo";
import type { StartupState } from "./bindings/StartupState";
import type { UpdateInfo } from "./bindings/UpdateInfo";
import type { UpdateOutcome } from "./bindings/UpdateOutcome";
import type { UpdatePolicy } from "./bindings/UpdatePolicy";
import type { UpdateStage } from "./bindings/UpdateStage";
import type { ScreenRole } from "./bindings/ScreenRole";
import type { ScreenSolutionInfo } from "./bindings/ScreenSolutionInfo";
import type { ScreenSpec } from "./bindings/ScreenSpec";
import type { SessionMode } from "./bindings/SessionMode";
import type { DeviceStatus } from "./bindings/DeviceStatus";
import type { LengthUnit } from "./bindings/LengthUnit";
import type { MonitorInfo } from "./bindings/MonitorInfo";
import type { MonitorPitch } from "./bindings/MonitorPitch";
import type { PixelRect } from "./bindings/PixelRect";
import type { ParsedLength } from "./bindings/ParsedLength";
import type { IpcError } from "./bindings/IpcError";

export type {
  AccentPreset,
  AdapterInfo,
  AdapterPreview,
  AppInfo,
  ConfigInspection,
  AppliedAdapterInfo,
  BackupInfo,
  CaptureResult,
  CapturedLayout,
  Confidence,
  FileDiff,
  MissingKey,
  ValueChange,
  AvailableModes,
  AxisReading,
  ConfirmOutcome,
  ConfirmState,
  DisplayMode,
  HotkeyInfo,
  SnapshotEntry,
  TopologyChange,
  TopologyPreview,
  TopologyProblem,
  TopologySnapshot,
  BestFitInfo,
  CurveResult,
  DesktopLayoutInfo,
  DetectedDevice,
  DeviceStatus,
  FixAction,
  GlassLevel,
  InputFrame,
  InputStatus,
  InstalledGameInfo,
  LicenceState,
  Tier,
  IpcError,
  Necessity,
  PendingSession,
  PeripheralRequirement,
  Platform,
  Profile,
  ProfileCard,
  ReadinessGate,
  ReadyState,
  Severity,
  StepStatus,
  StepView,
  UtilitySpec,
  OpenWindow,
  RectMeans,
  WindowResult,
  LoadedPreferences,
  LengthUnit,
  MonitorInfo,
  MonitorPitch,
  ParsedLength,
  Preferences,
  PixelRect,
  RigModel,
  RigSolutionInfo,
  RigWarningInfo,
  ScreenRole,
  ScreenSolutionInfo,
  ScreenSpec,
  SessionMode,
  StartupState,
  UpdateInfo,
  UpdateOutcome,
  UpdatePolicy,
  UpdateStage,
};

export const appInfo = () => invoke<AppInfo>("app_info");

/**
 * The frontend has something to show: close the splash and reveal the window.
 *
 * Called once, from the first render backed by real data. The main window
 * starts hidden precisely so this decides when it appears — showing it earlier
 * means a white rectangle the size of the window, which is exactly what the
 * splash exists to prevent.
 */
export const ready = () => invoke<void>("ready");

/** Read from the registry, not remembered — Windows disables these itself. */
export const startupState = () => invoke<StartupState>("startup_state");

export const setRunAtStartup = (enabled: boolean) =>
  invoke<StartupState>("set_run_at_startup", { enabled });

// -------------------------------------------------------------------- updates

/**
 * Ask whether a newer version exists. Downloads nothing.
 *
 * A build with no signing key configured says so rather than checking nothing
 * and reporting "up to date".
 */
export const checkForUpdate = () => invoke<UpdateInfo>("check_for_update");

/**
 * Download, verify, install, restart.
 *
 * The signature is checked against the key compiled into the running binary
 * before any of the new version runs. Refused while a session is in flight.
 */
export const installUpdate = () => invoke<void>("install_update");

/**
 * Where an install has got to.
 *
 * An update ends with the app being replaced, so a button that greys out and
 * says nothing reads as a crash. Every phase arrives here, failures included —
 * both callers used to discard them.
 */
export function onUpdateStage(handler: (stage: UpdateStage) => void): Promise<UnlistenFn> {
  return listen<UpdateStage>("updates://stage", (e) => handler(e.payload));
}

export const listMonitors = () => invoke<MonitorInfo[]>("list_monitors");

export const listDevices = () => invoke<DetectedDevice[]>("list_devices");

/** Ask for an immediate rescan. The result arrives via onDevicesChanged. */
export const refreshDevices = () => invoke<void>("refresh_devices");

/**
 * Subscribe to peripheral changes.
 *
 * The backend watches for device arrival and removal at the OS level and
 * publishes only when a debounced status actually changes — so this fires on
 * real events, not on a timer, and a USB device bouncing during enumeration
 * never reaches the UI.
 */
// --------------------------------------------------------- window control

// ---------------------------------------------------------------- preflight

/**
 * Run a saved profile's preflight. The launch phase is *not* started — that
 * waits for launchGame(), which is the deliberate second click.
 */
export const startPreflight = (profileId: string) =>
  invoke<StepView[]>("start_preflight", { profileId });

export const cancelPreflight = () => invoke<void>("cancel_preflight");

// ------------------------------------------------------------------ recovery

/**
 * The session that did not finish, if there is one.
 *
 * A session changes things outside the app. If it is killed mid-flight — crash,
 * power cut, Task Manager — nothing is left running to put them back, so a
 * marker on disk is what lets a later start notice and offer.
 */
export const pendingSession = () => invoke<PendingSession | null>("pending_session");

/** Undo what the unfinished session changed. */
export const recoverSession = () => invoke<string[]>("recover_session");

/** Leave it alone and stop asking. */
export const dismissPendingSession = () => invoke<void>("dismiss_pending_session");

/** Re-run one step and everything downstream of it, actions and all. */
export const retryStep = (id: number) => invoke<void>("retry_step", { id });

/** Stop a step blocking the gate. The row stays Skipped, never Passed. */
export const skipStep = (id: number) => invoke<void>("skip_step", { id });

/**
 * The second click. `force` is "race anyway" — it skips whatever is still
 * failing so the gate opens.
 */
export const launchGame = (force: boolean) => invoke<void>("launch_game", { force });

// ----------------------------------------------------------------- profiles

/**
 * The Games tab: every profile, with what is true of it on this machine now.
 *
 * Scans for installed games and makes a profile for any that lacks one, so
 * there is no separate "create" step. A profile outlives its install — an
 * uninstalled game keeps its card, marked not installed, with everything you
 * configured still in it.
 */
export const gameLibrary = () => invoke<ProfileCard[]>("game_library");

/**
 * Save a window rectangle onto a profile.
 *
 * The rectangle is one you have watched work, read back off a real window —
 * which is what makes automatic placement a replay rather than a gamble.
 */
export const rememberWindow = (args: {
  id: string;
  rect: PixelRect;
  means: RectMeans;
  exeName: string | null;
}) => invoke<Profile>("remember_window", args);

/**
 * Copy a running game's screen setup onto its profile.
 *
 * For rigs that are already set up — with SRWE, Resize Raccoon or by hand.
 * Reads the window's rectangle, whether it is frameless and always-on-top, and
 * the executable it belongs to; saves all of it and switches automatic
 * placement on, because the rectangle is working on screen at that moment.
 *
 * Pass `hwnd` only to answer a `choose` result.
 */
export const captureWindow = (id: string, hwnd?: string) =>
  invoke<CaptureResult>("capture_window", { id, hwnd: hwnd ?? null });

/** Turn automatic window placement on or off for one profile. */
export const setAutoApply = (id: string, enabled: boolean) =>
  invoke<Profile>("set_auto_apply", { id, enabled });

export const saveProfile = (profile: Profile) => invoke<Profile>("save_profile", { profile });

export const deleteProfile = (id: string) => invoke<void>("delete_profile", { id });

/**
 * Add a game the launchers do not know about.
 *
 * Steam and Epic are found automatically; everything else is not — iRacing has
 * its own updater, and a title bought direct has no manifest anywhere. Naming
 * the executable up front also gives the launcher something to watch for and
 * the window matcher something to find.
 */
export const addGame = (name: string, exePath: string) =>
  invoke<Profile>("add_game", { name, exePath });

/**
 * Step status changes.
 *
 * The checklist is a pure view over this stream — it never drives the
 * sequencing, which is what lets a self-healing check turn green on its own by
 * the same path the first result took.
 */
export function onStep(handler: (step: StepView) => void): Promise<UnlistenFn> {
  return listen<StepView>("launch://step", (e) => handler(e.payload));
}

export function onLaunchState(handler: (state: ReadyState) => void): Promise<UnlistenFn> {
  return listen<ReadyState>("launch://state", (e) => handler(e.payload));
}

export const listWindows = () => invoke<OpenWindow[]>("list_windows");

export const placeWindow = (args: {
  hwnd: string;
  rect: PixelRect;
  means: RectMeans;
  borderless: boolean;
  watch: boolean;
}) => invoke<WindowResult>("place_window", args);

export const stopWatchingWindow = () => invoke<void>("stop_watching_window");

export const startInputMonitor = (instancePath: string) =>
  invoke<void>("start_input_monitor", { instancePath });

/**
 * Stop watching one device.
 *
 * The path matters: a stop for a device that is no longer the one being
 * monitored is ignored, so a panel closing cannot kill the panel that replaced
 * it.
 */
export const stopInputMonitor = (instancePath: string) =>
  invoke<void>("stop_input_monitor", { instancePath });

/**
 * Live axis and button values for the monitored device.
 *
 * Throttled to about 30 frames a second in Rust — sim hardware reports at
 * 1000 Hz and forwarding all of it would be pure IPC traffic for motion no
 * screen can show.
 */
export function onInput(handler: (frame: InputFrame) => void): Promise<UnlistenFn> {
  return listen<InputFrame>("peripherals://input", (e) => handler(e.payload));
}

/**
 * What the monitor is doing.
 *
 * `start_input_monitor` returns as soon as the reading thread is spawned, so
 * its Ok says nothing about whether the device opened. Everything that can go
 * wrong afterwards — a refused HID path, a device with no input reports, a
 * session suspending the monitor — arrives here instead of in the log.
 */
export function onInputStatus(handler: (status: InputStatus) => void): Promise<UnlistenFn> {
  return listen<InputStatus>("peripherals://input-status", (e) => handler(e.payload));
}

export function onDevicesChanged(
  handler: (devices: DetectedDevice[]) => void,
): Promise<UnlistenFn> {
  return listen<DetectedDevice[]>("peripherals://changed", (e) => handler(e.payload));
}

/** Null when no monitors are detected at all — not an empty desktop. */
export const desktopLayout = () => invoke<DesktopLayoutInfo | null>("desktop_layout");

// ------------------------------------------------------------------ adapters

/**
 * The adapters that exist, and how well each one's key names are known.
 *
 * Confidence is on the wire on purpose: "read out of the shipped file" and
 * "corroborated across second-hand sources" are different claims, and the UI
 * must not make them look alike.
 */
export const listAdapters = () => invoke<AdapterInfo[]>("list_adapters");

/** What an adapter would write, and what is already correct. Reads only. */
export const previewAdapter = (args: {
  adapterId: string;
  rig: RigModel;
  session: SessionMode;
}) => invoke<AdapterPreview>("preview_adapter", args);

/**
 * What a title's config files actually contain — names only, never values.
 *
 * How a recognised-but-unconfirmed title becomes a real adapter: read the
 * structure here, send it in, and it becomes a catalog entry backed by a real
 * file rather than a forum post.
 */
export const inspectAdapter = (adapterId: string) =>
  invoke<ConfigInspection[]>("inspect_adapter", { adapterId });

/** Back up, then write. Resolves to the backup id, so this write alone can be undone. */
export const applyAdapter = (args: { adapterId: string; rig: RigModel; session: SessionMode }) =>
  invoke<AppliedAdapterInfo>("apply_adapter", args);

/** Every backup, newest first. */
export const listBackups = () => invoke<BackupInfo[]>("list_backups");

/** Put one operation's files back exactly as they were. */
export const restoreBackup = (id: string) => invoke<string[]>("restore_backup", { id });

// ------------------------------------------------------------ display control

/** Every mode each output can run, per output — never the union of them. */
export const availableModes = () => invoke<AvailableModes[]>("available_modes");

/** The desktop as it is now, in the shape a plan takes. */
export const currentTopology = () => invoke<TopologySnapshot>("current_topology");

/** What a plan would do and what is wrong with it. Writes nothing. */
export const previewTopology = (plan: TopologySnapshot) =>
  invoke<TopologyPreview>("preview_topology", { plan });

/**
 * Apply a plan and start the countdown.
 *
 * Resolves to a list of differences when the desktop did not end up matching
 * what was asked for — in which case it has already been put back, and no
 * countdown is running. An empty list means the change is live and waiting to
 * be confirmed.
 */
export const applyTopology = (plan: TopologySnapshot) =>
  invoke<string[]>("apply_topology", { plan });

/** Keep the pending change. Ends the countdown. */
export const keepTopology = () => invoke<void>("keep_topology");

/** Put it back now, without waiting for the countdown. */
export const revertTopology = () => invoke<void>("revert_topology");

/** What the panic hotkey is, and whether it actually registered. */
export const panicHotkey = () => invoke<HotkeyInfo>("panic_hotkey");

export const listSnapshots = () => invoke<TopologySnapshot[]>("list_snapshots");

/** Apply a stored snapshot. Goes through the same countdown as any change. */
export const restoreSnapshot = (id: string) => invoke<string[]>("restore_snapshot", { id });

/**
 * The countdown, and how it ended.
 *
 * Owned by Rust, not by this timer: if the change made the screen unreadable
 * there is nobody here to run a clock, and silence has to mean revert.
 */
export function onConfirmState(handler: (state: ConfirmState) => void): Promise<UnlistenFn> {
  return listen<ConfirmState>("display://confirm", (e) => handler(e.payload));
}

export const getPreferences = () => invoke<LoadedPreferences>("get_preferences");

export const savePreferences = (preferences: Preferences) =>
  invoke<LoadedPreferences>("save_preferences", { preferences });

export const accentPresets = () => invoke<AccentPreset[]>("accent_presets");

// --------------------------------------------------------------- diagnostics

/**
 * Build a diagnostics bundle. Resolves to where it landed.
 *
 * The bundle carries its own README listing everything in it and what was
 * redacted — a bundle people are afraid of is one nobody sends.
 */
export const createDiagnostics = () => invoke<string>("create_diagnostics");

/** Show a file in Explorer. Restricted in Rust to the app's own data folder. */
export const revealFile = (path: string) => invoke<void>("reveal_file", { path });

// ----------------------------------------------------------------- licensing

/**
 * The current entitlement, and the whole of what the frontend is told.
 *
 * No key, no token, no endpoint, no machine id — this bundle ships as readable
 * JavaScript, so anything the UI can see, anyone can read.
 */
export const licenceState = () => invoke<LicenceState>("licence_state");



// ------------------------------------------------------------------- the rig

export const listRigs = () => invoke<RigModel[]>("list_rigs");

/** Never null: falls back to a rig built from the monitors plugged in now. */
export const currentRig = () => invoke<RigModel>("current_rig");

export const saveRig = (rig: RigModel) => invoke<RigModel>("save_rig", { rig });

export const deleteRig = (id: string) => invoke<void>("delete_rig", { id });

/** Re-read the monitors, keeping every measurement already entered. */
export const detectRig = (existing: RigModel | null) =>
  invoke<RigModel>("detect_rig", { existing });

/** Solve without saving, so the numbers update as fields change. */
export const solveRig = (rig: RigModel, session: SessionMode) =>
  invoke<RigSolutionInfo>("solve_rig", { rig, session });

export const fitRig = (rig: RigModel, session: SessionMode) =>
  invoke<BestFitInfo | null>("fit_rig", { rig, session });

export const parseLength = (input: string, unit: LengthUnit) =>
  invoke<ParsedLength>("parse_length", { input, unit });

export const solveCurvature = (args: {
  arcOrChordMm: number;
  radiusMm: number | null;
  measuredAsChord: boolean;
  eyeDistanceMm: number;
}) => invoke<CurveResult>("solve_curvature", args);

/**
 * Tauri rejects with whatever the command's error type serialised to. Ours is
 * always an IpcError, but a panic or a missing command yields a bare string, so
 * narrow rather than assume.
 */
export function asIpcError(e: unknown): IpcError {
  if (typeof e === "object" && e !== null && "kind" in e && "message" in e) {
    return e as IpcError;
  }
  return { kind: "unknown", message: String(e), remedy: null };
}
