/**
 * The typed IPC client. This is the *only* place the frontend talks to Rust.
 *
 * Payload types come from `src/bindings/`, which is generated by ts-rs from the
 * Rust models — never hand-edited. The thin wrappers below exist so command
 * names appear exactly once in the frontend; `scripts/check-ipc.mjs` asserts
 * that every `#[tauri::command]` in Rust has a wrapper here and vice versa, so
 * a renamed or removed command fails CI instead of failing at runtime.
 */
import { invoke } from "@tauri-apps/api/core";
import { listen, type UnlistenFn } from "@tauri-apps/api/event";

import type { AccentPreset } from "./bindings/AccentPreset";
import type { AppInfo } from "./bindings/AppInfo";
import type { AxisReading } from "./bindings/AxisReading";
import type { BestFitInfo } from "./bindings/BestFitInfo";
import type { CurveResult } from "./bindings/CurveResult";
import type { DesktopLayoutInfo } from "./bindings/DesktopLayoutInfo";
import type { DetectedDevice } from "./bindings/DetectedDevice";
import type { GlassLevel } from "./bindings/GlassLevel";
import type { InputFrame } from "./bindings/InputFrame";
import type { InstalledGameInfo } from "./bindings/InstalledGameInfo";
import type { OpenWindow } from "./bindings/OpenWindow";
import type { RectMeans } from "./bindings/RectMeans";
import type { WindowResult } from "./bindings/WindowResult";
import type { LoadedPreferences } from "./bindings/LoadedPreferences";
import type { Preferences } from "./bindings/Preferences";
import type { RigModel } from "./bindings/RigModel";
import type { RigSolutionInfo } from "./bindings/RigSolutionInfo";
import type { RigWarningInfo } from "./bindings/RigWarningInfo";
import type { ScreenRole } from "./bindings/ScreenRole";
import type { ScreenSolutionInfo } from "./bindings/ScreenSolutionInfo";
import type { ScreenSpec } from "./bindings/ScreenSpec";
import type { SessionMode } from "./bindings/SessionMode";
import type { DeviceStatus } from "./bindings/DeviceStatus";
import type { LengthUnit } from "./bindings/LengthUnit";
import type { MonitorInfo } from "./bindings/MonitorInfo";
import type { MonitorPitch } from "./bindings/MonitorPitch";
import type { PixelRect } from "./bindings/PixelRect";
import type { ParsedLength } from "./bindings/ParsedLength";
import type { IpcError } from "./bindings/IpcError";

export type {
  AccentPreset,
  AppInfo,
  AxisReading,
  BestFitInfo,
  CurveResult,
  DesktopLayoutInfo,
  DetectedDevice,
  DeviceStatus,
  GlassLevel,
  InputFrame,
  InstalledGameInfo,
  IpcError,
  OpenWindow,
  RectMeans,
  WindowResult,
  LoadedPreferences,
  LengthUnit,
  MonitorInfo,
  MonitorPitch,
  ParsedLength,
  Preferences,
  PixelRect,
  RigModel,
  RigSolutionInfo,
  RigWarningInfo,
  ScreenRole,
  ScreenSolutionInfo,
  ScreenSpec,
  SessionMode,
};

export const appInfo = () => invoke<AppInfo>("app_info");

export const listMonitors = () => invoke<MonitorInfo[]>("list_monitors");

export const listDevices = () => invoke<DetectedDevice[]>("list_devices");

/** Ask for an immediate rescan. The result arrives via onDevicesChanged. */
export const refreshDevices = () => invoke<void>("refresh_devices");

/**
 * Subscribe to peripheral changes.
 *
 * The backend watches for device arrival and removal at the OS level and
 * publishes only when a debounced status actually changes — so this fires on
 * real events, not on a timer, and a USB device bouncing during enumeration
 * never reaches the UI.
 */
// --------------------------------------------------------- window control

export const discoverGames = () => invoke<InstalledGameInfo[]>("discover_games");

export const listWindows = () => invoke<OpenWindow[]>("list_windows");

export const placeWindow = (args: {
  hwnd: string;
  rect: PixelRect;
  means: RectMeans;
  borderless: boolean;
  watch: boolean;
}) => invoke<WindowResult>("place_window", args);

export const stopWatchingWindow = () => invoke<void>("stop_watching_window");

export const startInputMonitor = (instancePath: string) =>
  invoke<void>("start_input_monitor", { instancePath });

export const stopInputMonitor = () => invoke<void>("stop_input_monitor");

/**
 * Live axis and button values for the monitored device.
 *
 * Throttled to about 30 frames a second in Rust — sim hardware reports at
 * 1000 Hz and forwarding all of it would be pure IPC traffic for motion no
 * screen can show.
 */
export function onInput(handler: (frame: InputFrame) => void): Promise<UnlistenFn> {
  return listen<InputFrame>("peripherals://input", (e) => handler(e.payload));
}

export function onDevicesChanged(
  handler: (devices: DetectedDevice[]) => void,
): Promise<UnlistenFn> {
  return listen<DetectedDevice[]>("peripherals://changed", (e) => handler(e.payload));
}

/** Null when no monitors are detected at all — not an empty desktop. */
export const desktopLayout = () => invoke<DesktopLayoutInfo | null>("desktop_layout");

export const getPreferences = () => invoke<LoadedPreferences>("get_preferences");

export const savePreferences = (preferences: Preferences) =>
  invoke<LoadedPreferences>("save_preferences", { preferences });

export const accentPresets = () => invoke<AccentPreset[]>("accent_presets");

// ------------------------------------------------------------------- the rig

export const listRigs = () => invoke<RigModel[]>("list_rigs");

/** Never null: falls back to a rig built from the monitors plugged in now. */
export const currentRig = () => invoke<RigModel>("current_rig");

export const saveRig = (rig: RigModel) => invoke<RigModel>("save_rig", { rig });

export const deleteRig = (id: string) => invoke<void>("delete_rig", { id });

/** Re-read the monitors, keeping every measurement already entered. */
export const detectRig = (existing: RigModel | null) =>
  invoke<RigModel>("detect_rig", { existing });

/** Solve without saving, so the numbers update as fields change. */
export const solveRig = (rig: RigModel, session: SessionMode) =>
  invoke<RigSolutionInfo>("solve_rig", { rig, session });

export const fitRig = (rig: RigModel, session: SessionMode) =>
  invoke<BestFitInfo | null>("fit_rig", { rig, session });

export const parseLength = (input: string, unit: LengthUnit) =>
  invoke<ParsedLength>("parse_length", { input, unit });

export const solveCurvature = (args: {
  arcOrChordMm: number;
  radiusMm: number | null;
  measuredAsChord: boolean;
  eyeDistanceMm: number;
}) => invoke<CurveResult>("solve_curvature", args);

/**
 * Tauri rejects with whatever the command's error type serialised to. Ours is
 * always an IpcError, but a panic or a missing command yields a bare string, so
 * narrow rather than assume.
 */
export function asIpcError(e: unknown): IpcError {
  if (typeof e === "object" && e !== null && "kind" in e && "message" in e) {
    return e as IpcError;
  }
  return { kind: "unknown", message: String(e), remedy: null };
}
